### ISSUE TITLE
parser library error

### ISSUE THREAD

**Issue by alucard13s** [beaston02/CamsterRecorder#1] opened 2017-07-22 13:14 UTC
hi, i have successully installes bs4 package but when i lanch it's tell me to install a parser library with an error on line 64 and 24.
i have make a screen of the error.
![error camster](https://user-images.githubusercontent.com/30068831/28491364-257a2746-6ef0-11e7-869e-fba5b9c059c2.PNG)

if you can help me, thanks in advance and thanks for all your amazing work.

**Comment by beaston02** [comment] 2017-07-22 16:24
Im replying from my phone, so Im sorry for not having a more detailed solution. 

I forgot to include lxml on the setup instructions. try running `python3.5 -m pip install lxml` and see if that fixes the problem.

if it does not, I would suggest you google the error (the last portion, "Couldn't find a tree builder....Do you need to install  parser library?) and see what it suggests for windows. I don't run windows and Im not familiar with it, but you don't seem to have lxml installed. 

Please report back and let me know if the code I suggested worked, or if you otherwise get it fixed, and if so, how. Ill look into the proper solution for windows when I get a chance if you have not yet reported back. 

Thank you

**Comment by beaston02** [comment] 2017-07-29 13:49
Closing due to no additional updates or info provided. Ill assume this was fixed

**Closed as completed by beaston02** 2017-07-29 13:49 UTC

**Comment by alucard13s** [comment] 2017-07-29 14:23
hi, before you close, i have a another problem that i just forget.
The fix worked but it have a another error 
![capture camster](https://user-images.githubusercontent.com/30068831/28745512-1259189a-747a-11e7-8b50-ae3c115f062c.PNG)
From all your work it's the onlyone who make this message.
Can you see it's syntax error or anything else. Thanks in advance.

**Comment by beaston02** [comment] 2017-07-29 14:37
Is this a common problem? Or do the recordings usually work? From that output, it looks like its simply unable to create a connection to the link. This could either be caused by a simple network problem which can occur for reasons outside of the scripts control, or it could be something has changed and the paths to the streams may be that something. If its a one off, or rather rare occurrence, I could create some better error handling, if its a regular thing, Ill need to look into if the streams have changed. 

Thanks for the info

**Comment by beaston02** [comment] 2017-07-29 15:29
It looks like they changed the URL where the video is located. I made the changes so it should now work. 

Thank you for reporting. Please open a new issue if if you have any new problems
